server:
   port:10080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123456
    drive-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    
    
    
mybatis:
  type-aliases-package: cn.shop.base.login.entity
  mapper-locations: classpath:mapper/*.xml